In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-2.1408e+35,  4.5834e-41, -2.1408e+35],
        [ 4.5834e-41,         nan,  0.0000e+00],
        [ 7.6194e+31,  1.5564e+28,  1.8484e+31],
        [ 1.8370e+25,  1.4603e-19,  2.7517e+12],
        [ 7.5338e+28,  3.0313e+32,  6.3828e+28]])


In [4]:
x = torch.rand(5,3)
x

tensor([[0.8510, 0.0126, 0.2543],
        [0.9973, 0.0521, 0.8346],
        [0.1662, 0.7320, 0.2862],
        [0.3183, 0.8323, 0.3126],
        [0.2790, 0.6803, 0.0266]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [8]:
x = torch.ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.3047, -1.1749,  0.1725],
        [-0.3353, -1.4797, -0.0488],
        [-0.2295, -2.3086,  0.4680],
        [ 0.2725,  0.5308, -0.8444],
        [-0.9842, -0.7299,  1.1032]])

In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5,3)
y

tensor([[0.0456, 0.3942, 0.6151],
        [0.2472, 0.3162, 0.8401],
        [0.3153, 0.5225, 0.9930],
        [0.5797, 0.6955, 0.5820],
        [0.5212, 0.0881, 0.4553]])

In [13]:
x+y

tensor([[ 1.3503, -0.7807,  0.7876],
        [-0.0881, -1.1635,  0.7913],
        [ 0.0858, -1.7861,  1.4609],
        [ 0.8522,  1.2263, -0.2624],
        [-0.4630, -0.6418,  1.5585]])

In [14]:
torch.add(x,y)

tensor([[ 1.3503, -0.7807,  0.7876],
        [-0.0881, -1.1635,  0.7913],
        [ 0.0858, -1.7861,  1.4609],
        [ 0.8522,  1.2263, -0.2624],
        [-0.4630, -0.6418,  1.5585]])

In [15]:
res = torch.empty(5,3)
res

tensor([[-2.1408e+35,  4.5834e-41, -3.5168e+32],
        [ 3.0756e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 4.6300e-01,  6.4181e-01,  1.5585e+00]])

In [16]:
torch.add(x,y, out=res)

tensor([[ 1.3503, -0.7807,  0.7876],
        [-0.0881, -1.1635,  0.7913],
        [ 0.0858, -1.7861,  1.4609],
        [ 0.8522,  1.2263, -0.2624],
        [-0.4630, -0.6418,  1.5585]])

In [17]:
y.add_(x)

tensor([[ 1.3503, -0.7807,  0.7876],
        [-0.0881, -1.1635,  0.7913],
        [ 0.0858, -1.7861,  1.4609],
        [ 0.8522,  1.2263, -0.2624],
        [-0.4630, -0.6418,  1.5585]])

In [18]:
x[:,1]

tensor([-1.1749, -1.4797, -2.3086,  0.5308, -0.7299])

In [19]:
x = torch.randn(4,4)
y = x.view(16)
y

tensor([-0.1357, -0.9854, -0.5276,  0.5186,  0.2734,  1.0311,  0.4557, -1.4281,
         0.4004, -2.7564, -1.3372, -1.9899,  0.3971, -0.9345,  1.0818, -0.5654])

In [20]:
z = x.view(-1,8)
z

tensor([[-0.1357, -0.9854, -0.5276,  0.5186,  0.2734,  1.0311,  0.4557, -1.4281],
        [ 0.4004, -2.7564, -1.3372, -1.9899,  0.3971, -0.9345,  1.0818, -0.5654]])

In [23]:
x.view(-1,8)

tensor([[-0.1357, -0.9854, -0.5276,  0.5186,  0.2734,  1.0311,  0.4557, -1.4281],
        [ 0.4004, -2.7564, -1.3372, -1.9899,  0.3971, -0.9345,  1.0818, -0.5654]])

In [24]:
x.size()

torch.Size([4, 4])

In [25]:
y.size()

torch.Size([16])

In [26]:
z.size()

torch.Size([2, 8])

In [27]:
x = torch.rand(1)
x

tensor([0.8940])

In [28]:
x.item()

0.8940288424491882

In [31]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [32]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [34]:
import numpy as np

In [35]:
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [36]:
np.add(a,1,out=a)

array([2., 2., 2., 2., 2.])

In [37]:
a

array([2., 2., 2., 2., 2.])

In [38]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.8940], device='cuda:0')
tensor([1.8940], dtype=torch.float64)
