In [1]:
from __future__ import print_function
import torch

In [3]:
x = torch.Tensor(5,3)
print(x)


 1.4138e+38  4.5911e-41  2.9427e-44
 3.2230e-44  0.0000e+00  0.0000e+00
 5.7858e-39  8.4490e-39  1.0194e-38
 1.0102e-38  7.3470e-39  9.6429e-39
 1.0653e-38  8.9082e-39  8.9082e-39
[torch.FloatTensor of size 5x3]



In [4]:
x = torch.rand(5,3)
x


 0.5559  0.6864  0.5369
 0.2504  0.2365  0.9216
 0.5012  0.3875  0.0380
 0.3658  0.8798  0.9894
 0.0691  0.7578  0.2286
[torch.FloatTensor of size 5x3]

In [5]:
print(x.size())

torch.Size([5, 3])


In [6]:
y = torch.rand(5,3)
print(x+y)


 1.2625  1.3874  1.1247
 0.3909  1.2077  1.2321
 0.6647  1.1701  0.1391
 0.6405  1.4457  1.7899
 0.7049  1.5644  1.1272
[torch.FloatTensor of size 5x3]



In [8]:
print(torch.add(x,y))


 1.2625  1.3874  1.1247
 0.3909  1.2077  1.2321
 0.6647  1.1701  0.1391
 0.6405  1.4457  1.7899
 0.7049  1.5644  1.1272
[torch.FloatTensor of size 5x3]



In [9]:
result = torch.Tensor(5,3)
print(result)
torch.add(x,y,out=result)
print(result)


 0.0000e+00  0.0000e+00  8.0154e-43
 0.0000e+00  7.0065e-45  0.0000e+00
-1.7326e+18  6.9504e-43  0.0000e+00
 0.0000e+00  7.0065e-45  0.0000e+00
-1.7328e+18  6.9504e-43  0.0000e+00
[torch.FloatTensor of size 5x3]


 1.2625  1.3874  1.1247
 0.3909  1.2077  1.2321
 0.6647  1.1701  0.1391
 0.6405  1.4457  1.7899
 0.7049  1.5644  1.1272
[torch.FloatTensor of size 5x3]



In [16]:
y.add(x)
print(y)


 1.8183  2.0738  1.6616
 0.6413  1.4443  2.1537
 1.1659  1.5575  0.1770
 1.0063  2.3255  2.7792
 0.7739  2.3222  1.3557
[torch.FloatTensor of size 5x3]



In [12]:
y.add_(x)
print(y)


 1.8183  2.0738  1.6616
 0.6413  1.4443  2.1537
 1.1659  1.5575  0.1770
 1.0063  2.3255  2.7792
 0.7739  2.3222  1.3557
[torch.FloatTensor of size 5x3]



In [36]:
y[:,:2]


 1.8183  2.0738
 0.6413  1.4443
 1.1659  1.5575
 1.0063  2.3255
 0.7739  2.3222
[torch.FloatTensor of size 5x2]

In [44]:
x = torch.randn(4,4)
print(x)
print(x.size())


 0.2760 -0.0333 -2.3881 -1.5055
 0.1316 -0.3198 -1.3679 -0.1182
 0.0204 -0.6678  0.5594 -0.3388
 1.3303 -0.9025  1.3145  0.0526
[torch.FloatTensor of size 4x4]

torch.Size([4, 4])


In [43]:
y = x.view(16)
print(y.size())

torch.Size([16])


In [45]:
z = x.view(-1,8)
print(z.size())

torch.Size([2, 8])


In [46]:
a = torch.ones(5)
a


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

In [47]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [48]:
import numpy as np
c = np.ones(5)
c

array([ 1.,  1.,  1.,  1.,  1.])

In [49]:
type(a)

torch.FloatTensor

In [50]:
type(b)

numpy.ndarray

In [51]:
a.add_(1)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

In [52]:
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [53]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



In [54]:
a = np.ones(5)
print(a)

[ 1.  1.  1.  1.  1.]


In [55]:
b = torch.from_numpy(a)
b


 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

In [56]:
np.add(a,1, out=a)
a

array([ 2.,  2.,  2.,  2.,  2.])

In [57]:
b


 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

## NOTE: All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [58]:
if(torch.cuda.is_available()):
    print("CUDA AVAILABLE")
    x = x.cuda()
    y =y.cuda()
    

In [60]:
from torch.autograd import Variable

In [63]:
x = Variable(torch.ones(2,2), requires_grad= True)
x

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [64]:
y = x+2
y

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [65]:
print(y.grad_fn)

In [80]:
z = y*y*3
out = z.mean()
print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [81]:
out.backward()

In [82]:
x

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [83]:
print(x.grad)

Variable containing:
 13.5000  13.5000
 13.5000  13.5000
[torch.FloatTensor of size 2x2]



In [84]:
out

Variable containing:
 27
[torch.FloatTensor of size 1]

In [ ]:
x = torch.rand(3)
x = Variable

In [86]:
y = torch.rand(3,3)
y


 0.3170  0.0177  0.7126
 0.1545  0.0218  0.2878
 0.1738  0.4739  0.3485
[torch.FloatTensor of size 3x3]

In [87]:
z = torch.randn(3,3)
z


-0.0923  1.1529 -0.3936
-0.3782  0.2245  1.0289
 0.6344  0.8819 -0.2496
[torch.FloatTensor of size 3x3]

In [97]:
q = torch.random.initial_seed()
q

1517564036

In [99]:
x = torch.randn(3)
x = Variable(x,requires_grad = True)
y = x*2
while y.data.norm() < 10000:
    y = y*2
print(y)

Variable containing:
 10807.3164
  3138.1050
 -1841.8519
[torch.FloatTensor of size 3]



In [100]:
gradient = torch.FloatTensor([0.1,1.0,0.0001])
y.backward(gradient)
print(x.grad)

Variable containing:
  819.2000
 8192.0000
    0.8192
[torch.FloatTensor of size 3]

