In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))
    

In [3]:
import torch 
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[6.8250e-21, 4.5783e-41, 3.5201e-36],
        [3.0948e-41, 4.4842e-44, 0.0000e+00]])


In [3]:
describe(torch.rand(2,3)) # uniform random
describe(torch.randn(2,3)) # random normal

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.0782, 0.4356, 0.4603],
        [0.0123, 0.1864, 0.8258]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[ 0.1509,  0.1616, -0.6545],
        [ 0.6144,  0.2903, -1.0277]])


In [4]:
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [5]:
x = torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
import numpy as np

npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.8297, 0.5691, 0.2037],
        [0.8939, 0.6471, 0.3202]], dtype=torch.float64)


In [7]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [8]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
x = torch.Tensor([[1,2,3],[4,5,6]], dtype=torch.int64)
describe(x)

TypeError: new() received an invalid combination of arguments - got (list, dtype=torch.dtype), but expected one of:
 * (torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (object data, torch.device device)
      didn't match because some of the keywords were incorrect: dtype


In [15]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Tensor Operations

In [16]:
x = torch.randn(2,3)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-0.8694, -1.0235,  1.2421],
        [ 0.8875, -0.3531,  1.4955]])


In [17]:
describe(torch.add(x,x))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-1.7387, -2.0471,  2.4843],
        [ 1.7751, -0.7062,  2.9910]])


In [18]:
describe(x+x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-1.7387, -2.0471,  2.4843],
        [ 1.7751, -0.7062,  2.9910]])


In [19]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [20]:
x = x.view(2,3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [21]:
describe(torch.sum(x, dim=0))

Type: torch.LongTensor
Shape/Size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [22]:
describe(torch.sum(x, dim=1))

Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [23]:
describe(torch.transpose(x,0,1))

Type: torch.LongTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [24]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

## Indexing Slicing and Joining

In [28]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [29]:
x = torch.arange(6).view(2,3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [32]:
describe(x[:1, :2])

Type: torch.LongTensor
Shape/Size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [33]:
describe(x[0, 1])

Type: torch.LongTensor
Shape/Size: torch.Size([])
Values: 
1


In [34]:
indices = torch.LongTensor([0,2])
indices

tensor([0, 2])

In [35]:
describe(torch.index_select(x, dim=1,index=indices))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [37]:
indices = torch.LongTensor([0,0])
describe(torch.index_select(x, dim=0,index=indices))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [38]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: 
tensor([0, 4])


In [40]:
x = torch.arange(6).view(2,3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [41]:
describe(torch.cat([x,x], dim=0))

Type: torch.LongTensor
Shape/Size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [42]:
describe(torch.cat([x,x], dim=1))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [43]:
describe(torch.stack([x,x]))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [44]:
x1 = torch.arange(6).view(2,3)
describe(x1)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [49]:
x2 = torch.ones(3,2)
x2[:,1] += 1
describe(x2)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [50]:
describe(torch.mm(x1,x2))

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'mat2'

## Tensor and computational Graph

In [51]:
x = torch.ones(2,2, requires_grad=True)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [52]:
print(x.grad is None)

True


In [53]:
y = (x+2) * (x+5) + 3
describe(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [54]:
z = y.mean()
describe(z)
z.backward()
print(z.grad is None)

Type: torch.FloatTensor
Shape/Size: torch.Size([])
Values: 
21.0
True


In [55]:
print(x.grad is None)

False


## Cuda Tensors

In [4]:
torch.cuda.is_available()

False

In [5]:
torch.backends.cudnn.enabled

True

In [6]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [8]:
x = torch.randn(3,3).to(device)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 3])
Values: 
tensor([[ 1.6235,  2.1147, -0.1065],
        [ 0.2201,  1.3432, -0.4816],
        [ 0.6660, -0.3003,  0.0838]])


In [9]:
y = torch.rand(3,3)
x+y

tensor([[1.9164, 3.0697, 0.5661],
        [0.9840, 1.4991, 0.4380],
        [1.4696, 0.4517, 0.6945]])

In [10]:
cpu_device = torch.device("cpu")

1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.

In [23]:
a = torch.rand(3,3)

In [24]:
a.unsqueeze(0)

tensor([[[0.2808, 0.7398, 0.7614],
         [0.0917, 0.0490, 0.2379],
         [0.5882, 0.7163, 0.3083]]])

In [22]:
a.unsqueeze(1)

tensor([[[0.7604, 0.9407, 0.4647]],

        [[0.3498, 0.2888, 0.0322]],

        [[0.9268, 0.1076, 0.1894]]])

In [17]:
x = torch.Tensor([1,2,3,4])

In [18]:
x

tensor([1., 2., 3., 4.])

In [19]:
x.unsqueeze(0)

tensor([[1., 2., 3., 4.]])

In [20]:
x.unsqueeze(1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])

2: Remove the extra dimension you just added to the previous tensor.

In [28]:
a = torch.rand(3,3)
a

tensor([[0.5512, 0.6611, 0.0634],
        [0.0415, 0.9519, 0.8757],
        [0.7370, 0.7146, 0.4668]])

In [29]:
a = a.unsqueeze(0)
a

tensor([[[0.5512, 0.6611, 0.0634],
         [0.0415, 0.9519, 0.8757],
         [0.7370, 0.7146, 0.4668]]])

In [30]:
a.squeeze(0)
a

tensor([[[0.5512, 0.6611, 0.0634],
         [0.0415, 0.9519, 0.8757],
         [0.7370, 0.7146, 0.4668]]])

3: Create a random tensor of shape 5x3 in the interval [3, 7)

In [32]:
a = torch.Tensor(5,3)
a

tensor([[ 6.8250e-21,  4.5783e-41,  6.8250e-21],
        [ 4.5783e-41,  0.0000e+00,  0.0000e+00],
        [ 1.0272e-28,  1.1211e+22,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-1.0757e-22, -2.8288e+37,  0.0000e+00]])

In [33]:
a = a*(7-3)
a

tensor([[ 2.7300e-20,  1.8313e-40,  2.7300e-20],
        [ 1.8313e-40,  0.0000e+00,  0.0000e+00],
        [ 4.1090e-28,  4.4843e+22,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-4.3026e-22, -1.1315e+38,  0.0000e+00]])

In [34]:
a = 3*a
a

tensor([[ 8.1899e-20,  5.4940e-40,  8.1899e-20],
        [ 5.4940e-40,  0.0000e+00,  0.0000e+00],
        [ 1.2327e-27,  1.3453e+23,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-1.2908e-21, -3.3945e+38,  0.0000e+00]])

In [35]:
3 + torch.rand(5, 3) * (7 - 3)

tensor([[5.7288, 6.9685, 3.7263],
        [6.3901, 6.2878, 5.2424],
        [5.9972, 6.4799, 3.6350],
        [3.7162, 4.9607, 4.2837],
        [3.6126, 3.3509, 6.7133]])

4: Create a tensor with values from a normal distribution (mean=0, std=1).

In [36]:
a = torch.randn(3,3)
a

tensor([[-0.3466, -0.7780, -1.5078],
        [ 1.2478,  0.1940, -1.0700],
        [ 0.8072, -2.0118, -0.9939]])

In [38]:
a.normal_()

tensor([[ 1.0499,  0.4951, -1.3322],
        [ 0.3506,  0.4344,  0.3180],
        [ 0.2091, -0.2166,  3.2057]])

In [39]:
a

tensor([[ 1.0499,  0.4951, -1.3322],
        [ 0.3506,  0.4344,  0.3180],
        [ 0.2091, -0.2166,  3.2057]])

5: Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).

In [40]:
a = torch.Tensor([1, 1, 1, 0, 1])
a

tensor([1., 1., 1., 0., 1.])

In [41]:
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

6: Create a random tensor of size (3,1) and then horizontally stack 4 copies together

In [42]:
a = torch.rand(3,1)
a

tensor([[0.5588],
        [0.4779],
        [0.5364]])

In [44]:
a.expand(3,4)
a


tensor([[0.5588],
        [0.4779],
        [0.5364]])

7: Return the batch matrix-matrix product of two 3-dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).

In [47]:
a=torch.rand(3,4,5); b=torch.rand(3,5,4)

In [48]:
a
b

tensor([[[0.2597, 0.9223, 0.9551, 0.5495],
         [0.2223, 0.2502, 0.4838, 0.8725],
         [0.3479, 0.0539, 0.2053, 0.6268],
         [0.4946, 0.6870, 0.2573, 0.7263],
         [0.4274, 0.4686, 0.5765, 0.8630]],

        [[0.0924, 0.3607, 0.1377, 0.7237],
         [0.8470, 0.7067, 0.1578, 0.3974],
         [0.8749, 0.5921, 0.9257, 0.1282],
         [0.6498, 0.1039, 0.2939, 0.4910],
         [0.2016, 0.2723, 0.0131, 0.4311]],

        [[0.8075, 0.3255, 0.4763, 0.2067],
         [0.8227, 0.2134, 0.3323, 0.2182],
         [0.7071, 0.1779, 0.7543, 0.2960],
         [0.3020, 0.6461, 0.4318, 0.4758],
         [0.5611, 0.1635, 0.7822, 0.1706]]])

In [49]:
torch.bmm(a,b)

tensor([[[1.1168, 1.5295, 1.6355, 2.2962],
         [0.8959, 1.3791, 1.6218, 1.9936],
         [0.9779, 1.1283, 1.1650, 2.0758],
         [0.4671, 0.6615, 0.7379, 0.9858]],

        [[1.6163, 1.2311, 0.9028, 1.4735],
         [1.6574, 1.3635, 0.9276, 1.4122],
         [1.2019, 1.0762, 0.5704, 0.9418],
         [1.4573, 1.3947, 0.7114, 1.4183]],

        [[0.9773, 0.7858, 1.0398, 0.6848],
         [1.3264, 0.8705, 1.4980, 0.7464],
         [1.3623, 0.6465, 1.2427, 0.5465],
         [0.8051, 0.5165, 0.9316, 0.4805]]])

8: Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [50]:
a=torch.rand(3,4,5); b=torch.rand(5,4)
a
b

tensor([[1.2511e-04, 4.8785e-01, 9.1302e-01, 5.2917e-02],
        [6.1482e-01, 8.3846e-01, 7.0098e-01, 2.1560e-02],
        [7.0112e-01, 2.9498e-01, 3.0539e-01, 8.3545e-01],
        [2.5866e-01, 8.9129e-01, 4.4250e-01, 7.1164e-01],
        [1.2989e-01, 7.4353e-01, 9.7163e-01, 1.5708e-01]])

In [51]:
torch.bmm(a, b.unsqueeze(0).expand(a.size(0),*b.size()))

tensor([[[0.9369, 1.1258, 1.1253, 0.6359],
         [0.7446, 1.7224, 1.6268, 0.6348],
         [0.6153, 1.3016, 1.2367, 1.0940],
         [1.1520, 1.4914, 1.5257, 0.9982]],

        [[1.0713, 1.2319, 1.3638, 0.8974],
         [1.1395, 2.0460, 1.9120, 1.1285],
         [0.5773, 1.3087, 1.5384, 0.7468],
         [1.2355, 1.9182, 1.7205, 1.0163]],

        [[0.9801, 1.7036, 1.8588, 0.6676],
         [0.7383, 1.4713, 1.6324, 0.6431],
         [0.4592, 1.2945, 1.2912, 0.5497],
         [0.7618, 1.7150, 2.0394, 0.6314]]])